# -------------------------------------------------------------------
# Métadonnées globales
# -------------------------------------------------------------------
name: festival_app # nom de ton application
description: App Festival Strasbourg DI5

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

# -------------------------------------------------------------------
# Dépendances
# -------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  carousel_slider_plus: ^7.1.1

  # Icons iOS style
  cupertino_icons: ^1.0.8

  # Scanner & galerie
  mobile_scanner: ^3.2.0
  image_picker: ^1.1.1

  # Décodage QR depuis image
  qr_code_dart_decoder: ^0.1.2

  # Connexion internet
  connectivity_plus: ^6.0.5

  # Permissions
  permission_handler: ^11.3.0

  # Internationalisation
  intl: any

  wechat_assets_picker: ^10.1.0


  # ==== AJOUTÉS  ====
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  in_app_purchase: ^3.2.0
  path_provider: ^2.1.4

# -------------------------------------------------------------------
# Dev dépendances
# -------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# -------------------------------------------------------------------
# Flutter configuration
# -------------------------------------------------------------------
flutter:
  assets:
    - assets/images/
    - assets/images/program/
    - assets/images/program/jurys/
    - assets/images/daily/


  uses-material-design: true
